[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_token_staking = "BESn7mK1YzUMGjdW8V5msezxN51ZuoxUnjMkGTUSPTHW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
